# For pip caching see documentation here:
# https://docs.gitlab.com/ee/ci/caching/#caching-python-dependencies
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
cache:
  key: "$CI_JOB_NAME"
  paths:
    - .cache/pip

stages:
  - lint
  - test
default:
  before_script:
    - pip install -U pip setuptools wheel
    - python -V
lint:
  stage: lint
  image: python:3.7
  script:
    - pip install tox
    - tox -e lint
pytest:
  stage: test
  image: python:3.7
  coverage: '/^TOTAL.+?(\d+\%)$/'
  script:
    - pip install --no-cache-dir $(grep 'torch==' requirements.txt)
    - pip install -r requirements.txt
    - pip install ".[dev]"
    - pytest
